export {
  Auxweave_DOC_VERSION,
  Auxweave_STORAGE_KEY,
  type AuxweaveDocument,
  type AuxweaveDocumentStorageKind,
  type AuxweavePage,
  activateAuxweavePage,
  cloneAuxweaveDocument,
  cloneAuxweavePage,
  createAuxweavePage,
  createEmptyAuxweaveDocument,
  createEmptyAuxweavePage,
  getAuxweaveDocumentStorageKind,
  parseAuxweaveDocument,
  type SceneArrow,
  type SceneGroup,
  type SceneIcon,
  type SceneImage,
  type SceneLine,
  type SceneObject,
  type ScenePolygon,
  type SceneRect,
  type SceneStar,
  type SceneText,
  type SceneVectorBoard,
  syncActivePage,
} from './auxweave-scene'
